In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
credits_path = '/content/drive/MyDrive/CIS550_GroupProject/Movies_Metadata/credits.csv'
credits = pd.read_csv(credits_path)
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [ ]:
import ast 
credits['ast_cast'] = credits['cast'].apply(lambda x: ast.literal_eval(str(x)))
credits['ast_crew'] = credits['crew'].apply(lambda x: ast.literal_eval(str(x)))

In [ ]:
credits

,cast,crew,id,ast_cast,ast_crew
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357,"[{'cast_id': 1, 'character': 'Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."
...,...,...,...,...,...
45471,"[{'cast_id': 0, 'character': '', 'credit_id': ...","[{'credit_id': '5894a97d925141426c00818c', 'de...",439050,"[{'cast_id': 0, 'character': '', 'credit_id': ...","[{'credit_id': '5894a97d925141426c00818c', 'de..."
45472,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",111109,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de..."
45473,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",67758,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de..."
45474,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",227506,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de..."
45475,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",461257,[],"[{'credit_id': '593e676c92514105b702e68e', 'de..."

In [ ]:
credits['ast_crew'][0]

In [ ]:
credits['ast_cast'][1][0]

{'cast_id': 1,
 'character': 'Alan Parrish',
 'credit_id': '52fe44bfc3a36847f80a7c73',
 'gender': 2,
 'id': 2157,
 'name': 'Robin Williams',
 'order': 0,
 'profile_path': '/sojtJyIV3lkUeThD7A2oHNm8183.jpg'}

In [ ]:
all_movies_cast = []
for i in range(len(credits)) :
  id = credits.loc[i, 'id']
  cast_list = credits.loc[i, 'ast_cast']
  m = len(cast_list)
  movie_cast = []
  for cast in cast_list: 
    name = cast['name']
    gender = cast['gender']
    character = cast['character']
    movie_cast.append([id, name, gender, character])
  all_movies_cast.extend(movie_cast)
all_movies_cast

In [ ]:
df_cast = pd.DataFrame(all_movies_cast, columns = ['movie_id', 'cast_name', 'gender', 'character'])
df_cast

In [ ]:
df_cast.to_csv (r'/content/drive/MyDrive/CIS550_GroupProject/Movies_Metadata/cast.csv', index = False, header=True)

In [ ]:
all_movies_crew = []
for i in range(len(credits)) :
  id = credits.loc[i, 'id']
  crew_list = credits.loc[i, 'ast_crew']
  m = len(crew_list)
  movie_crew = []
  for crew in crew_list: 
    name = crew['name']
    gender = crew['gender']
    job = crew['job']
    department = crew['department']
    movie_crew.append([id, name, gender, job, department])
  all_movies_crew.extend(movie_crew)
all_movies_crew

In [ ]:
df_crew = pd.DataFrame(all_movies_crew, columns = ['movie_id', 'cast_name', 'gender', 'job', 'department'])
print(df_crew)
df_crew.to_csv (r'/content/drive/MyDrive/CIS550_GroupProject/Movies_Metadata/crew.csv', index = False, header=True)

In [ ]:
keywords_path = '/content/drive/MyDrive/CIS550_GroupProject/Movies_Metadata/keywords.csv'
keywords = pd.read_csv(keywords_path)
keywords.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [ ]:
keywords['ast_keywords'] = keywords['keywords'].apply(lambda x: ast.literal_eval(str(x)))
keywords.head()

In [ ]:
keywords['ast_keywords'][0]

[{'id': 931, 'name': 'jealousy'},
 {'id': 4290, 'name': 'toy'},
 {'id': 5202, 'name': 'boy'},
 {'id': 6054, 'name': 'friendship'},
 {'id': 9713, 'name': 'friends'},
 {'id': 9823, 'name': 'rivalry'},
 {'id': 165503, 'name': 'boy next door'},
 {'id': 170722, 'name': 'new toy'},
 {'id': 187065, 'name': 'toy comes to life'}]

In [ ]:
all_movies_keywords = []
for i in range(len(keywords)) :
  id = keywords.loc[i, 'id']
  keywords_list = keywords.loc[i, 'ast_keywords']
  m = len(keywords_list)
  movie_keywords = []
  for keyword in keywords_list: 
    key = keyword['name']
    movie_keywords.append([id, key])
  all_movies_keywords.extend(movie_keywords)
all_movies_keywords

In [ ]:
df_keywords = pd.DataFrame(all_movies_keywords, columns = ['movie_id', 'tag'])
print(df_keywords)
df_keywords.to_csv (r'/content/drive/MyDrive/CIS550_GroupProject/Movies_Metadata/tags.csv', index = False, header=True)

In [ ]:
meta_path = '/content/drive/MyDrive/CIS550_GroupProject/Movies_Metadata/ratings_small.csv'
ratings = pd.read_csv(meta_path)
ratings.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [ ]:
from datetime import datetime
all_movies_ratings = []
for i in range(len(ratings)) :
  id = ratings.loc[i, 'movieId']
  user_id = ratings.loc[i, 'userId']
  rating = ratings.loc[i, 'rating']
  timestamp = ratings.loc[i, 'timestamp']
  date = datetime.fromtimestamp(timestamp)
  all_movies_ratings.append([id, user_id, rating, date])
all_movies_ratings

In [ ]:
df_ratings = pd.DataFrame(all_movies_ratings, columns = ['movie_id', 'user_id', 'rating', 'date'])
print(df_ratings)
df_ratings.to_csv (r'/content/drive/MyDrive/CIS550_GroupProject/Movies_Metadata/ratings_db.csv', index = False, header=True)

        movie_id  user_id  rating                date
0             31        1     2.5 2009-12-14 02:52:24
1           1029        1     3.0 2009-12-14 02:52:59
2           1061        1     3.0 2009-12-14 02:53:02
3           1129        1     2.0 2009-12-14 02:53:05
4           1172        1     4.0 2009-12-14 02:53:25
...          ...      ...     ...                 ...
99999       6268      671     2.5 2003-10-08 02:16:10
100000      6269      671     4.0 2003-10-03 02:46:41
100001      6365      671     4.0 2003-12-09 03:26:03
100002      6385      671     2.5 2003-12-09 14:21:03
100003      6565      671     3.5 2004-01-22 15:18:44

[100004 rows x 4 columns]

In [ ]:
links_path = '/content/drive/MyDrive/CIS550_GroupProject/Movies_Metadata/links_small.csv'
links = pd.read_csv(links_path)
links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [ ]:
all_movies_links = []
for i in range(len(links)) :
  id = links.loc[i, 'movieId']
  user_id = links.loc[i, 'imdbId']
  tmdb_id = links.loc[i, 'tmdbId']
  all_movies_links.append([id, user_id, tmdb_id])
all_movies_links

In [ ]:
df_links = pd.DataFrame(all_movies_links, columns = ['movie_id', 'imdb_id', 'tmdb_id'])
print(df_links)
df_links.to_csv (r'/content/drive/MyDrive/CIS550_GroupProject/Movies_Metadata/links_db.csv', index = False, header=True)

In [3]:
meta_path = '/content/drive/MyDrive/CIS550_GroupProject/Movies_Metadata/movies_metadata.csv'
meta = pd.read_csv(meta_path)
meta.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
meta.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
from datetime import datetime
dt_str = meta['release_date'][0]
print(dt_str)
date_time_obj = datetime.strptime(dt_str, '%Y-%m-%d')

1995-10-30

In [69]:
from datetime import datetime
all_movies_meta = []
for i in range(len(meta)) :
  id = meta.loc[i, 'id']
  dt_str = meta.loc[i, 'release_date']
  #print(dt_str)
  try:
    rel_date = datetime.strptime(dt_str, '%Y-%m-%d')
  except:
    rel_date = pd.NaT
  title = meta.loc[i, 'original_title']
  revs = meta.loc[i, 'revenue']
  try: 
    budget = float(meta.loc[i, 'budget'])
  except ValueError: 
    budget = pd.NA
  coll = meta.loc[i, 'belongs_to_collection']
  overview = meta.loc[i, 'overview']
  tagline = meta.loc[i, 'tagline']
  runtime = meta.loc[i, 'runtime']
  lang = meta.loc[i, 'original_language']
  imdb_id = meta.loc[i, 'imdb_id']
  vote = meta.loc[i, 'vote_average']
  all_movies_meta.append([id, title, revs, rel_date, budget, overview, tagline, runtime, lang, imdb_id, vote, coll])
#all_movies_meta

In [ ]:
all_movies_meta

In [ ]:
df_meta = pd.DataFrame(all_movies_meta, columns = ['movie_id', 'title', 'revs', 'release_date', 'budget', 'overview', 'tagline', 'runtime', 'lang', 'imdb_id', 'vote'])
print(df_meta)
df_meta.to_csv (r'/content/drive/MyDrive/CIS550_GroupProject/Movies_Metadata/meta_db.csv', index = False, header=True)

In [ ]:
all_movies_paths = []
for i in range(len(meta)) :
  id = meta.loc[i, 'id']
  path = ast.literal_eval(df_meta.loc[0, 'coll'])['poster_path']
  all_movies_paths.append([id, path])
all_movies_paths

In [35]:
import ast 
ast.literal_eval(meta['genres'][0])

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]

In [ ]:
all_movies_genres = []
for i in range(len(meta)) :
  id = meta.loc[i, 'id']
  genres = ast.literal_eval(str(meta.loc[i, 'genres']))
  for genre in genres:
    all_movies_genres.append([id, genre['name']])
all_movies_genres

In [ ]:
df_genres = pd.DataFrame(all_movies_genres, columns = ['movie_id', 'genre'])
print(df_genres)
df_genres.to_csv (r'/content/drive/MyDrive/CIS550_GroupProject/Movies_Metadata/genres_db.csv', index = False, header=True)

In [ ]:
import json 
from bson import json_util

def parse_json(data):
    return json.loads(json_util.dumps(data))

with open('/content/drive/MyDrive/CIS550_GroupProject/Posters/Info/test.txt', 'r') as file:
  data = file.read()
  #print(data)
  d = (parse_json(data))
  print(d[22])

5

In [ ]:
file = open('/content/drive/MyDrive/CIS550_GroupProject/Posters/Info/test.txt', 'r')
data = file.read()
print(data)

{
  "_id" : ObjectId("56fb860e71a0651b0c306f56"),
  "Language" : "English",
  "Box_office" : "101,500,000",
  "Country" : "USA",
  "Rated" : "R",
  "imdbID" : "tt0081562",
  "Awards" : "1 nomination.",
  "Poster" : "http://ia.media-imdb.com/images/M/MV5BMTM4OTI3MTYxNl5BMl5BanBnXkFtZTcwMTA1NDkyMQ@@._V1_SX300.jpg",
  "Director" : "Sidney Poitier",
  "Released" : "12 Dec 1980",
  "Writer" : "Bruce Jay Friedman",
  "imdbVotes" : "17,705",
  "Runtime" : "111 min",
  "Response" : "True",
  "imdbRating" : "6.8",
  "Title" : "Stir Crazy",
  "Genre" : "Comedy, Crime",
  "Actors" : "Gene Wilder, Richard Pryor, Georg Stanford Brown, JoBeth Williams",
  "Type" : "movie",
  "Metascore" : "50"
}
{
  "_id" : ObjectId("56fb860e71a0651b0c306f55"),
  "Language" : "English",
  "Box_office" : "290,158,751",
  "Country" : "USA",
  "Rated" : "PG",
  "imdbID" : "tt0080684",
  "Awards" : "Won 1 Oscar. Another 15 wins & 18 nominations.",
  "Poster" : "http://ia.media-imdb.com/images/M/MV5BMjE2MzQwMTgxN15BMl5BanBnXkFtZTcwMDQzNjk2OQ@@._V1_SX300.jpg",
  "Director" : "Irvin Kershner",
  "Released" : "20 Jun 1980",
  "Writer" : "Leigh Brackett (screenplay), Lawrence Kasdan (screenplay), George Lucas (story)",
  "imdbVotes" : "799,579",
  "Runtime" : "124 min",
  "Response" : "True",
  "imdbRating" : "8.8",
  "Title" : "Star Wars: Episode V - The Empire Strikes Back",
  "Genre" : "Action, Adventure, Fantasy",
  "Actors" : "Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams",
  "Type" : "movie",
  "Metascore" : "79"
}

In [ ]:
# possible resources: https://stackoverflow.com/questions/66934442/how-to-use-python-to-extract-the-keywords-in-json-format-data
# will update more here